# Generated by Django 3.2.4 on 2021-07-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('post_body', models.TextField(blank=True, null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
