# Generated by Django 3.2.5 on 2021-08-24 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
