# Generated by Django 3.2.5 on 2021-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
