# Generated by Django 3.2.4 on 2021-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_name', models.CharField(max_length=150)),
                ('cover_pic', models.IntegerField(blank=True, null=True)),
                ('type_group', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('about_group', models.CharField(max_length=600)),
            ],
        ),
    ]
