# Generated by Django 3.2.5 on 2021-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('type_group', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('about_group', models.CharField(max_length=600)),
            ],
        ),
    ]
