# Generated by Django 3.2.5 on 2021-08-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-created_date']},
        ),
    ]
