# Generated by Django 3.2.4 on 2021-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
