# Generated by Django 3.2.5 on 2021-08-24 20:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='about_group',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
