# Generated by Django 3.2.5 on 2021-08-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_about_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='about_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
